### ISSUE TITLE
无法生成略缩图

### ISSUE THREAD

**Issue by GHZhi** [DG-Wangtao/FFMEVideoPlayer#2]
使用原来的FFMPEG，在MediaElement的RenderingVideo事件中可以使用   e.Bitmap.CreateDrawingBitmap()方法生成System.Drawing.Btiamp。但是这个库经过修改，e.Btimap是.WriteableBitmap类型，需要经过转换才能取到Drawing.Bitmap。且某些视频获取略缩图有一定概率会是空白，不清楚这个库的源码是怎样处理的。

**Comment by DG-Wangtao** [comment]
Hi，关于这个问题，我觉的你可以看一下https://github.com/unosquare/ffmediaelement这个库

**Comment by GHZhi** [comment]
这个已经解决了哈，使用ffmpeg命令的方式生成比较稳定。

**Comment by DG-Wangtao** [comment]
好的，那这个issue我就关闭啦～

**Comment by GHZhi** [comment]
关闭吧，不过如果能生成当然是更好啦。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wangtao"<notifications@github.com&gt;; 
发送时间: 2020年8月31日(星期一) 中午11:56
收件人: "DG-Wangtao/FFMEVideoPlayer"<FFMEVideoPlayer@noreply.github.com&gt;; 
抄送: "q.Zhi"<243422176@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [DG-Wangtao/FFMEVideoPlayer] 无法生成略缩图 (#2)





 
好的，那这个issue我就关闭啦～
 
&mdash;
